---
#file: jenkins.yaml
- hosts: jenkins-slave 
  become: true
  tasks:
   - name: To create required directory structure
     file:
       path: /var/jenkins 
       state: directory
       mode: '0755'
   - name: Download file with checksum url (sha256)
     get_url:
       url: http://172.17.0.1:8080/jnlpJars/slave.jar 
       dest: /usr/bin/slave.jar 
   - name: Install apt
     apt:
       name: "{{ slave_modules }}"
       state: present
