---
# tasks file for git
- name: To set user name
  git_config:
    name: user.name 
    scope: global
    value: "{{ myname }}" 
    state: present
- name: To set user email 
  git_config:
    name: user.email
    scope: global
    value: "{{ mymail }}" 
    state: present
- name: To set git ui color 
  git_config:
    name: color.ui
    value: auto
