---
galaxy_info:
  role_name: docker
  author: Marcel Akkerman
  description: Docker on Ubuntu
  company: viewsource.nl
  issue_tracker_url: https://github.com/akkerman/ansible-docker/issues
  license: license (BSD, MIT)
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - docker

dependencies: []
